stages:
    - test
    - development
    
test_branch:
    stage: test
    script: echo proses berjalan
    
development_branch:
    stage: development
    only: 
        - development
    script:
        - cd /var/www/sman5bdg/front-learn-vuejs
        - git pull origin development
        - sudo npm run build